# Generated by Django 4.1.6 on 2023-02-10 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_user_trial_ends_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='telegram_id',
        ),
    ]
